{
 "title": "Kafka clients",
 "description": "Dashboards for Kafka clients metrics",
 "tags": [ "0.0.1" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(cp_zookeeper_initlimit, release)"
   }
  ]
 },
 "panels": [
  { "title": "Kafka Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quorum Size",
   "type": "singlestat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cp_zookeeper_quorumsize{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "singlestat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cp_zookeeper_numaliveconnections{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "response_rate",
   "type": "graph",
   "description": "Responses received by Producer from Broker per second.\nDepending on your configuration, “received” could mean a couple of things:\nThe message was received, but not committed (request.required.acks == 0)\nThe leader has written the message to disk (request.required.acks == 1)\nThe leader has received confirmation from all replicas that the data has been written to disk (request.required.acks == -1)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "producer_metrics_response_rate", "legendFormat": "{{client_id}}" }
   ]
  },
  {
   "title": "request_rate",
   "type": "graph",
   "description": "The average number of requests sent per second.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "producer_metrics_request_rate", "legendFormat": "{{client_id}}" }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cp_zookeeper_inmemorydatatree_nodecount{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "singlestat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cp_zookeeper_inmemorydatatree_watchcount{release=~\"$Release\"})"
    }
   ]
  },
  {
   "title": "io_ratio",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "producer_metrics_io_ratio", "legendFormat": "{{client_id}}" }
   ]
  },
  {
   "title": "io_wait_ratio",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "producer_metrics_io_wait_ratio", "legendFormat": "{{client_id}}" }
   ]
  },
  {
   "title": "user processing time",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1- producer_metrics_io_wait_ratio - producer_metrics_io_ratio",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "request_latency_avg",
   "type": "graph",
   "description": "Kafka Broker Pods Memory Usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_request_latency_avg",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "outgoing_byte_rate",
   "type": "graph",
   "description": "The average number of outgoing bytes sent per second to all servers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "producer_metrics_outgoing_byte_rate",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}