global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: producer
    scrape_interval: 5s
    static_configs:
      - targets:
          - producer:8080
#  - job_name: 'producer'
#    dns_sd_configs:
#      - names: ['producer']
#        type: 'A'
#        port: 8080
#    metrics_path: /metrics
#    static_configs:
#      - targets:
#        - producer:8080